name: hextraj
channels:
  - conda-forge
dependencies:
  # Required for full project functionality (dont remove)
  - pytest
  # dependencies
  - xarray
  - numpy
  - scipy
  - dask
  - netcdf4
  - pandas
  - matplotlib
