name: test_env_hextraj
channels:
  - conda-forge
dependencies:
  - python=3
  - dask
  - distributed
  - git
  - htop
  - matplotlib
  - netcdf4
  - numpy
  - pre-commit
  - pyproj
  - pytest
  - scipy
  - seaborn
  - xarray
  - pip:
      - codecov
      - pytest-cov
      - coverage[toml]
