name: test_env_hextraj
channels:
  - conda-forge
dependencies:
  - python=3.11
  - git
  - ipython
  - numpy
  - pre-commit
  - pyproj
  - pytest
  - scipy
  - xarray
  - pip:
      - codecov
      - pytest-cov
      - coverage[toml]
