name: test_env_hextraj
channels:
  - conda-forge
dependencies:
  - python=3.9
  ############## These will have to be adjusted to your specific project
  - dask
  - numpy
  - pyproj
  - scipy
  - xarray
  ##############
  - pytest
  - pip:
      - codecov
      - pytest-cov
      - coverage[toml]
